# Generated by Django 4.2.1 on 2023-09-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainercard', '0004_alter_trainercard_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainercard',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics'),
        ),
    ]
