# Generated by Django 4.2.1 on 2023-09-24 07:28

from django.db import migrations, models
import trainercard.validator


class Migration(migrations.Migration):

    dependencies = [
        ('trainercard', '0005_alter_trainercard_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainercard',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics', validators=[trainercard.validator.validate_file_size]),
        ),
    ]
