# Generated by Django 4.2.1 on 2023-10-21 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainercard', '0007_poketeam_trainercard_poke_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainercard',
            name='poke_teams',
        ),
        migrations.AddField(
            model_name='trainercard',
            name='poke_team',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainercard.poketeam'),
        ),
        migrations.AlterField(
            model_name='poketeam',
            name='team_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
