# Generated by Django 4.2.1 on 2023-10-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainercard', '0007_poketeam_trainercard_poke_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainercard',
            name='poke_teams',
        ),
        migrations.AddField(
            model_name='trainercard',
            name='poke_teams',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainercard.poketeam'),
        ),
    ]
