# Generated by Django 4.2.1 on 2023-10-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainercard', '0008_remove_trainercard_poke_teams_trainercard_poke_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poketeam',
            name='team_name',
            field=models.CharField(max_length=15),
        ),
    ]
