# Generated by Django 4.2.1 on 2023-10-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainercard', '0008_remove_trainercard_poke_teams_trainercard_poke_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poketeam',
            name='team_name',
            field=models.CharField(default='My first Team', max_length=15),
        ),
    ]
