# Generated by Django 4.2.1 on 2023-07-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='number',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
