# Generated by Django 4.2.1 on 2023-07-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexapp', '0002_pokemon_name_pokemon_number_pokemon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='number',
        ),
    ]
