# Generated by Django 4.2.1 on 2023-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexapp', '0004_sprite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(null=True)),
            ],
        ),
    ]
